[package]
name = "cs2-schema-generated"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
nalgebra = { workspace = true }
serde = { version = "1.0.178", features = ["derive"] }
cs2-schema-cutl = { path = "../cutl" }
raw_struct = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
cs2-schema-definition = { path = "../definition" }
serde = { version = "1.0.178", features = ["derive"] }
serde_json = "1.0.104"
