[package]
name = "cs2-schema-generated"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
nalgebra = "0.32.3"
serde = { version = "1.0.178", features = ["derive"] }
cs2-schema-cutl = { path = "../cutl" }
raw_struct = { version = "0.1.3" }

[build-dependencies]
anyhow = "1.0.72"
cs2-schema-definition = { version = "0.1.0", path = "../definition" }
serde = { version = "1.0.178", features = ["derive"] }
serde_json = "1.0.104"
