[package]
name = "aimbot"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.30"
winapi = { version = "0.3", features = ["fileapi", "handleapi", "ioapiset", "synchapi", "errhandlingapi"] }
anyhow = "1.0"
