[package]
name = "cs2-schema-definition"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
serde = { version = "1.0.178", features = ["derive"] }
raw_struct = { version = "0.1.3" }
serde_json = "1.0.128"
