[package]
name = "cs2-schema-definition"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { version = "1.0.178", features = ["derive"] }
raw_struct = { workspace = true }
serde_json = "1.0.128"
