[package]
name = "cs2-schema-definition"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { version = "1.0.178", features = ["derive"] }
raw_struct = { workspace = true }
serde_json = "1.0.128"
